Add 2022-annual-review docs
karmada-io/community pull request #13
Opened 2022-10-17 11:37 UTC by Poor12

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add 2022-annual-review docs

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
None

2022-10-20 09:01 UTC, Poor12 commented
/cc @RainbowMango @kevin-wangzefeng

2022-10-22 13:10 UTC, lonelyCZ commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +| Zhe Cheng         | @lonelyCZ        | SEL-Zhejiang University | [531187475@qq.com](mailto:531187475@qq.com)                                       |
I have already applied for a Campus Email and may be able to use it.

```suggestion
| Zhe Cheng         | @lonelyCZ        | SEL-Zhejiang University | [chengzhe@zju.edu.cn](mailto:chengzhe@zju.edu.cn)                                       |
```

2022-10-24 04:29 UTC, Poor12 commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +| Reviewer/Approver | GitHub ID        | Affiliation             | Email                                                                             |
Add complete lists.

2022-10-24 06:57 UTC, Poor12 commented
/cc @Tingtal for grammar check

2022-10-24 12:48 UTC, kevin-wangzefeng commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Karmada was proposed and accepted as a sandbox project in September 2021. ([GitHub](https://github.com/cncf/toc/issues/721)).
```suggestion
Karmada was proposed and accepted as a sandbox project in September 2021.
Sandbox project onboarding issue: https://github.com/cncf/toc/issues/721
```

2022-10-24 12:48 UTC, kevin-wangzefeng commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +## Thriving Community
```suggestion
## Continous Community Momentum
```

2022-10-24 12:48 UTC, kevin-wangzefeng commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +In the past year, we joint effort with end users from multiple industries at birth and committed to building a more prosperous community.
> we joint effort with end users from multiple industries at birth

grammar mistake

2022-10-24 12:48 UTC, kevin-wangzefeng commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +continue to refine our documentation and use cases so that our users can get started with our project faster.
Provide more informations about the efforts we made to build closer connections between community and end users

2022-10-24 12:48 UTC, kevin-wangzefeng commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +
```suggestion
```


Unnecessary paragraph break here

2022-10-25 12:39 UTC, Tingtal requested changes
Language polishing comments

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* [Diverse developer ecosystem](#diverse-developer-ecosystem)
```suggestion
* [Robust Developer Ecosystem](#diverse-developer-ecosystem)
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* [Wide range of Adoption](#wide-range-of-adoption)
```suggestion
* [Extensive Adoption](#wide-range-of-adoption)
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* [Diverse developer ecosystem](#diverse-developer-ecosystem)
Not sure whether this part (#diverse-developer-ecosystem) can be changed. If yes, pls make the same change.

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* [Project goals](#project-goals)
```suggestion
* [Project Goals](#project-goals)
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* [How the CNCF Can Help](#how-the-cncf-can-help)
```suggestion
* [How CNCF Can Help](#how-the-cncf-can-help)
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Karmada (Kubernetes Armada) is a Kubernetes management system that enables you to run your cloud-native applications across multiple Kubernetes clusters and clouds, with no changes to your applicatio
```suggestion
Karmada (Kubernetes Armada) is a Kubernetes management system that enables you to run your cloud-native applications across multiple Kubernetes clusters and clouds, with no changes to your applications. Supporting Kubernetes-native APIs and advanced scheduling, Karmada realizes truly open, multi-cloud Kubernetes.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Karmada aims to provide turnkey automation for multi-cluster application management in multi-cloud and hybrid cloud scenarios, with key features such as centralized multi-cloud management, high avail
```suggestion
Karmada aims to provide turnkey automation for multi-cluster applications across multi-cloud and hybrid cloud deployments. Key features include centralized multi-cloud management, high availability, failure recovery, and traffic scheduling.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Karmada has built-in policy sets for multi-scenarios, enabling multi-dimensional and multi-level high-availability deployment of applications. At the same time, Karmada provides region-independent ce
```suggestion
Karmada provides default policy sets to ensure high application availability from multiple dimensions in different scenarios. Region-independent cluster management allows more flexible service deployment.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +The functionality and value of the Karmada project can be summarized at a very high level by these two main areas:
```suggestion
Karmada presents its value in the following two aspects:
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +1. Provide a smooth evolution path for native Kubernetes, so that Karmada-based multi-cloud solutions can be seamlessly integrated into the cloud-native technology ecosystem, and provide enterprises
```suggestion
1. Provides a smooth path for organizations to evolve from a single-cluster architecture to a multi-cloud one, while channeling the cloud native technology ecosystem to their native Kubernetes capabilities in use.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +2. Provide high-availability scheduling, failover, multi-cluster service discovery, multi-cloud cluster lifecycle management and other capability sets in a modular manner and
```suggestion
2. Provides functional modules covering HA scheduling, failover, multi-cluster service discovery, multi-cloud cluster lifecycle management, etc,
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +   preset policy sets for a variety of typical user scenarios which allows users to freely customize the multi-cloud platform that suits them according to the actual situation of the enterprise.
```suggestion
   as well as policy sets for a variety of scenarios, which allow users to customize their own multi-cloud platforms.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +## Continous Community Momentum
```suggestion
## Community Advances
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +In the past year, we joint effort with end users from multiple industries at birth and committed to building a more prosperous community.
```suggestion
In the past year, we joined hand with end users across industries and witnessed successful implementations of Karmada in many real-world projects.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +We have made a lot of efforts so that we can better communicate with users and understand the usage scenarios of users,
```suggestion
We have built channels to reach out to our users to know better what they want and need,
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +including holding meetups and online communication activities. Also, we
```suggestion
such as meetups and online activities. Also, we
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Before the Karmada project was born, we have been deeply involved in the Kubefed project led by the Kubernetes multi-cluster sig.
```suggestion
Before our journey of developing Karmada, we were deeply engaged in the Kubefed project led by the Kubernetes multi-cluster SIG.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Arguably, Karmada is developed in continuation of Kubernetes Federation v1 and v2 and also their natural successor. Some basic concepts are inherited from these two versions.
```suggestion
Such engagement brought us insights and expertise to develop Karmada. Karmada is built based on Kubernetes Federation v1 and v2 and inherits some basic concepts from them.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +In the past year, we continue to collaborate with upstream communities.
```suggestion
We also marked our presence in upstream communities.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +- We communicate closely with the Kubernetes community. We participated in and led the design of the [work api](https://github.com/kubernetes-sigs/work-api) in the multi-cluster aspect. Contribution
```suggestion
- In the Kubernetes community, we led the design of the [work API](https://github.com/kubernetes-sigs/work-api) for multi-cluster deployments. Our contributions make us the [maintainers of this project](https://github.com/kubernetes-sigs/work-api/blob/master/OWNERS).
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  We are also one of the earliest projects to apply the above api of the upstream community. Our users can easily use them in Karmada. For example, we provide [multi-cluster service discovery](https:
```suggestion
  We are also one of the earliest projects to adopt the above APIs of the upstream communities. Our users can easily use them in Karmada. For example, we provide [multi-cluster service discovery](https://karmada.io/docs/next/userguide/service/multi-cluster-service) based on multi-cluster service APIs.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +- Besides Kubernetes, we are open to intergration of more CNCF projects and already have some amazing integration cases. For specific integration cases, refer to [here](#rich-integration).
```suggestion
- Besides Kubernetes, we are open to intergration of more CNCF projects and already have some amazing cases (details available [here](#rich-integration)).
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Through the above efforts, the community has grown since the project entered the CNCF sandbox.
```suggestion
The above efforts take the community to a new height since the project entered the CNCF sandbox.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +From the data we can clearly see this trend.
```suggestion
Numbers can tell the story.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Karmada currently has [330+](https://karmada.devstats.cncf.io/d/18/overall-project-statistics-table?orgId=1&viewPanel=1) contributors from [50+](https://karmada.devstats.cncf.io/d/5/companies-table?o
```suggestion
Karmada currently has [330+](https://karmada.devstats.cncf.io/d/18/overall-project-statistics-table?orgId=1&viewPanel=1) contributors from [50+](https://karmada.devstats.cncf.io/d/5/companies-table?orgId=1) organizations across [14](https://karmada.devstats.cncf.io/d/18/overall-project-statistics-table?orgId=1&viewPanel=1) countries and regions.
```

2022-10-25 12:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +For specific developer data, refer to [Diverse developer ecosystem](#diverse-developer-ecosystem).
```suggestion
More details about our developers are available in [Diversifed Developer Ecosystem](#diversified-developer-ecosystem).
```

2022-10-26 04:14 UTC, Tingtal requested changes
Language polishing (part 2)

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* We held bi-weekly community meetings constantly (total 38 times as of September 2022). The meeting records can be found in [here](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DB
```suggestion
* We hold bi-weekly community meetings regularly (38 times as of September 2022), with about 25 attendees each time. Meeting minutes available [here](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit).
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* [Number of contributions](https://karmada.devstats.cncf.io/d/74/contributions-chart?orgId=1&var-period=m&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-company_name=All&va
```suggestion
* [Number of contributions](https://karmada.devstats.cncf.io/d/74/contributions-chart?orgId=1&var-period=m&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-company_name=All&var-company=all&from=now-1y&to=now&editPanel=5)) increased to **1,500+ per month**
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* [Github stars](https://karmada.devstats.cncf.io/d/3/stars-and-forks-by-repository?orgId=1) increased from **1600+ to 2600+**
```suggestion
* [GitHub stars](https://karmada.devstats.cncf.io/d/3/stars-and-forks-by-repository?orgId=1) increased from **1,600+ to 2,600+**
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* [Github forks](https://karmada.devstats.cncf.io/d/3/stars-and-forks-by-repository?orgId=1) increased from **200+ to 500+**
```suggestion
* [GitHub forks](https://karmada.devstats.cncf.io/d/3/stars-and-forks-by-repository?orgId=1) increased from **200+ to 500+**
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +## Diverse developer ecosystem
```suggestion
## Robust Developer Ecosystem
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +In the past year, we attach great importance to the development of developers.
```suggestion
We attach great importance to developers.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +We have established a mature mentor mechanism in the community. With the help of our tutors, quite a few active and qualified contributors have been promoted to members or maintainers.
```suggestion
We have established a mature mentor mechanism in the community. Some active and qualified contributors, mentored attentively, have been promoted to members or maintainers.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +In the past year, contributors to our project are steadily growing and a total of 182 contributors came from 50 different companies and organizations, showing the diversity of the community.
```suggestion
In the past year, our project expanded to 182 contributors from 50 different organizations, such as members from cloud vendors or academic institutions and individual developers,
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Among them, there are members from cloud vendors, members from academic institutions, and some independent developers.
```suggestion
showing the diversity of the community.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Among the contributors, there are **23** people recognized by the community as reviewers and approvers, and they still demonstrate the diversity and inclusion of the community.
```suggestion
Among the contributors, there are **23** people recognized by the community as reviewers and approvers.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Most of them are new contributors of our projects last year.
```suggestion
Most of contributors are newcomers to our project last year.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +We are very excited to see them grow in the community and look forward to them taking on greater responsibilities.
```suggestion
We are very excited to see them grow in the community and look forward to their greater contributions.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +## Wide range of Adoption
```suggestion
## Extensive Adoption
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Before the release of v1.0.0, we release every a month to bring users higher quality features. After v1.0.0, we have adjusted our update cadence to once every 3 months to make users experience more s
```suggestion
We once released new features every month. Starting from version 1.0.0, we changed our pace to every 3 months, with the aim to deliver more stable features and smooth upgrade.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +And the biggest accomplishment from the Karmada community in the past year is the release of v1.0.0, the first major milestone in the project’s history, which means the project is now stable and read
```suggestion
The biggest accomplishment of the community for the past year is the release of v1.0.0, the first milestone for the project, which means Karmada is now stable and ready to be used in production environments.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +We are glad that this is further validated by project adopters successfully running Karmada in production environments.
```suggestion
We are glad that this has been validated by project adopters successfully running Karmada in their own prod.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +With Karmada reaching maturity, we are seeing end-users adopt Karmada and find success running it in their production environments. We consistently hear from users that have adopted Karmada as the co
```suggestion
With Karmada reaching maturity, more and more users adopt Karmada as the core to build their multi-cloud and multi-cluster container orchestration engine for higher service efficiency.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +The community growth has been quite encouraging and we are pleased to be able to include specific details about some of their adoption success in the sections below.
```suggestion
The community is witnessing a promising growth. Some success cases provided below set a good example for future adopters.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Karmada now has 11 adopters that using Karmada in `production` environments until 2022/10/25.
```suggestion
Karmada now has 11 adopters that using Karmada in `production` environments as of Oct 25, 2022.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **VIPKID** is an online English education platform which delivers 150 million training sessions across countries and regions. To provide better services, VIPKID deploys applications by region and c
```suggestion
* **VIPKID** is an online English teaching platform which delivers 150 million sessions across countries and regions. To provide better services, VIPKID deploys applications by region closer to teachers and trainees.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  Therefore, VIPKID purchased dozens of clusters from multiple cloud providers around the world to build its internal infrastructure.
```suggestion
Therefore, VIPKID purchased dozens of clusters from multiple cloud vendors to build its global infrastructure.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  To solve the above problem, VIPKID finally chooses Karmada. In the words of Ci Yiheng, backend R&D Expert at VIPKID:
```suggestion
To solve this challenge, VIPKID chooses Karmada. Ci Yiheng, backend R&D expert at VIPKID, said:
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  How to manage multi-region and multi-vendor clusters has become a new challenge for VIPKID.
```suggestion
How to manage multi-region and multi-vendor clusters has become a new challenge for VIPKID.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  For now, the number of Kubernetes clusters in ICBC has reached more than **100** and the number of containers deployed has reached more than **280 thousand**. They are managed by the container clou
```suggestion
For now, ICBC is running over **100** Kubernetes clusters and more than **280,000** containers. They are managed by the container cloud platform in a unified manner. However, ICBC also faces the following four problems: 1) Limited availability. A Kubernetes cluster is also a fault domain, requiring automatic recovery across fault domains. 2) Limited resources. Application scheduling and auto scaling are available only to single clusters. 3) Non-transparent clusters. Upper-layer applications
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  are not aware of cluster differences. 4) Duplicate configuration. Although services are configured on the cloud management platform in a unified manner, the specific configuration needs to be deliv
```suggestion
are not aware of cluster differences. 4) Repeated operation. Although services are configured on the cloud management platform in a unified manner, their configurations need to be delivered to each cluster separately.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  To solve the above problem, ICBC finally chooses Karmada. In the words of Shen Yifan at ICBC:
```suggestion
  To solve these problems, ICBC chooses Karmada. Shen Yifan at ICBC said:
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  The complete use case can be found [here](https://karmada.io/zh/blog/2022/03/22/multi-cluster-management-with-an-ocean-of-nodes/).
```suggestion
The use case details can be found [here](https://karmada.io/zh/blog/2022/03/22/multi-cluster-management-with-an-ocean-of-nodes/).
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  The complete use case can be found [here](https://karmada.io/docs/next/casestudies/vipkid).
```suggestion
The use case details can be found [here](https://karmada.io/docs/next/casestudies/vipkid).
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **AIML INSTITUTE** is a tech company that helps enterprises build integrated cloud native solutions for digital transformation.  Built on Kubernetes, their platform is cloud-vendor-independent. Cus
```suggestion
* **AIML INSTITUTE** is a tech company that helps enterprises build integrated cloud native solutions for digital transformation. Built on Kubernetes, their platform is cloud-vendor-independent. Customers can host service applications without regard for vendor differences.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  However, their customers are demanding more and more on multi-cloud, and the scale and number of clusters and the O&M complexity grow sharply, they need to find a way to satisfy their customers. By
```suggestion
Their customers are demanding more on multicloud, and the O&M complexity increases sharply with the growing scale and number of clusters. The company needs to find a way to satisfy their customers. With Karmada, existing resource definitions can be migrated into multi-cluster environments without modification.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  The complete use case can be found [here](https://karmada.io/docs/next/casestudies/ci123).
```suggestion
The use case details can be found [here](https://karmada.io/docs/next/casestudies/ci123).
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **Huawei Cloud**'s UCS(Ubiquitous Cloud Native Service) has adopted Karmada to support unified access and unified management of cross-cloud and cross-region clusters. By using Karmada, UCS realizes
```suggestion
* **Huawei Cloud**'s UCS (Ubiquitous Cloud Native Service) adopts Karmada to connect and manage cross-cloud and cross-region clusters and the cloud native applications running in them.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  provides enterprises with a consistent global experience in cloud native business deployment, management, and application ecology.
```suggestion
UCS provides consistent experience in cloud native deployment, management, and application ecosystem.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  In the words of UCS:
```suggestion
  From the UCS team:
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  The complete use case can be found [here](https://support.huaweicloud.com/intl/en-us/productdesc-ucs/ucs_productdesc_0001.html).
```suggestion
The use case details can be found [here](https://support.huaweicloud.com/intl/en-us/productdesc-ucs/ucs_productdesc_0001.html).
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +In the past year, Karmada actively cooperates with other CNCF projects and helps them better transition to multi-cluster based on Kubernetes native API.
```suggestion
In the past year, Karmada actively cooperates with other CNCF projects and helps them better transition to multi-cluster based on Kubernetes native APIs.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +The following are examples of ecosystem projects that have collaborated and integrated with Karmada:
```suggestion
The following lists ecosystem projects integrated with Karmada:
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* [Velero](https://karmada.io/docs/administrator/backup/working-with-velero), which provides the ability to backup and migrate Kubernetes resource and persistent volumes can utilize Karmada to implem
```suggestion
* [Velero](https://karmada.io/docs/administrator/backup/working-with-velero), which uses Karmada to back up and migrate Kubernetes resources and persistent volumes across multiple clusters.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* [Istio](https://karmada.io/docs/userguide/service/working-with-istio-on-flat-network), the CNCF service mesh project can utilize Karmada to implement multi-cluster traffic governance in both flat a
```suggestion
* [Istio](https://karmada.io/docs/userguide/service/working-with-istio-on-flat-network), the CNCF service mesh project, which utilizes Karmada to implement multi-cluster traffic governance in both flat and non-flat network planes.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* In terms of multi-cluster observability, Karmada works with [Prometheus](https://karmada.io/docs/administrator/monitoring/working-with-prometheus) to build a multi-cloud unified monitoring view. An
```suggestion
* In terms of multi-cluster observability, Karmada works with [Prometheus](https://karmada.io/docs/administrator/monitoring/working-with-prometheus) to build a multi-cloud unified monitoring view. And [Filebeat](https://karmada.io/docs/administrator/monitoring/working-with-filebeat), which provides the ability to collect logs, utilizes Karmada to
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +## Project goals
```suggestion
## Project Goals
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +Following the above goals, the biggest goals at that time were quite simply to:
```suggestion
Following the above goals, we concentrated efforts on:
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* Build a extensible and open architecture and reach a stable core API and feature set that is reliable and mature
```suggestion
* Building an extensible, open architecture and a stable core API and feature set that is reliable and mature
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* Have production adopters that have successfully deployed Karmada into production environments
```suggestion
* Helping users to deploy Karmada in their production environments
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +In the last year we released a total of 1 major version and 6 minor versions. As we released v1.0.0 version, the Karmada project has entered a stage of steady iteration.
```suggestion
In the last year we released 1 major version and 6 minor versions. Version 1.0.0 marks a stage of steady iteration for the Karmada project.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +We are glad to see more and more users have begun to seriously adopt Karmada and run it in production scenarios with great success.
```suggestion
We are glad to see more and more users are adopting Karmada and running it in production successfully.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +For the past year's work, we summarize in the following points:
```suggestion
We summarize our work in the last year as follows:
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **More powerful cross-cluster scheduling capabilities**. In the last year, we have done a lot of work on cross-cluster scheduling of applications. Facing a variety of user scenarios, we introduced
```suggestion
* **More powerful cross-cluster scheduling capabilities**. In the last year, we have done a lot of work on cross-cluster scheduling of applications. Facing a variety of user scenarios, we introduced richer scheduling strategies and a new component named `karmada-scheduler-estimator` to improve scheduling accuracy.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  What's more, we introduced `karmada-descheduler` to reschedule in case of cluster resource imbalance. Based on this, users can deliver their applications more easily among clusters across regions a
```suggestion
What's more, we introduced `karmada-descheduler` to reschedule in case of cluster resource imbalance. Based on this, users can distribute their applications more easily among clusters across regions and vendors.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  - we enhance the framework of the resource interpreter to enable users to customize the resource status collected to the control plane.
```suggestion
  - We enhanced the framework of the resource interpreter to enable users to customize the resource status collected to the control plane.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +    Based on this, users no longer have to deal with tedious and repetitive configuration management, and no longer have to endure the management costs caused by fragmented API access portals.
```suggestion
    Based on this, users no longer have to deal with tedious and repetitive configuration management, nor to endure the management costs caused by fragmented API access portals.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **More convenient cross-cluster service governance**. In the past year, we support multi-cluster service discovery and an one-stop multi-cluster network solution. Now users can enable service gover
```suggestion
* **More convenient cross-cluster service governance**. We support multi-cluster service discovery and a one-stop multi-cluster network solution. Now users can enable service governance for cross-cluster with Karmada.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **High availability for multi-cloud applications**. In the past year, we support cross-cluster failover of applications.
```suggestion
* **High availability for multi-cloud applications**. We support cross-cluster failover of applications.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  When a cluster fails, applications can smoothly migrate from the failed cluster to another available cluster. During the replicas migration process, Karmada can ensure that the service replicas doe
```suggestion
When a cluster fails, applications can smoothly migrate from the failed cluster to another available cluster. During the replicas migration, Karmada ensures that the service replicas do not drop to zero, thereby ensuring that the service will not be interrupted.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  Based on this, users can use Karmada to manage distributed applications with confidence.
```suggestion
Based on this, users can use Karmada to manage distributed applications with confidence.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **Smoother multi-cluster O&M experience**. In the past year, we continue to optimize our command line tools. Now users can complete the creation of the Karmada control plane and bootstrap token-bas
```suggestion
* **Smoother multi-cluster O&M experience**. We continue to optimize our command line tools. Now users can complete the creation of the Karmada control plane and bootstrap token-based cluster registration in just a few clicks.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  Meanwhile, we provide not only a smooth upgrading path from the previous version but also a clear approach to migrate from Kubefed or promote legacy workload from Kubernetes.
```suggestion
Meanwhile, we provide not only a smooth version upgrade path but also a clear approach to migrate from Kubefed or promote legacy workloads from Kubernetes.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +The Karmada project continues to grow and has its sight on multiple goals for both the near term and long range:
```suggestion
The Karmada project continues to grow and has its sight on short-term and long-term goals:
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  - Karmada manages the cluster on the central side, which simplifies the tedious steps of cluster management but also brings some security risks.
```suggestion
  - Karmada manages clusters centrally, which eases cluster management but brings some security risks. 
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +    We should minimize the permissions of the control plane and reduce blast radius to member clusters after a control plane failure.
```suggestion
The aim is to minimize the permissions of the control plane and reduce blast radius to member clusters after a control plane failure.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  - Meanwhile, multi-cluster access control with high fine-grained security isolation on the control plane is also a major direction in the future.
```suggestion
  - Another target is on multi-cluster access control with finer-grained security isolation on the control plane.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **Performance to adapt to larger scale landing scenarios**. We have started an early effort around improving user experiences in large scale scenarios in the past releases.
```suggestion
* **Larger scale landing**. We have started early on improving user experience in large-scale scenarios in the past releases.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  Multiple cloud naturally means larger resource pools, which brings greater performance pressure to the multi-cloud management platform.
```suggestion
Multicloud means larger resource pools, which brings greater performance pressure to the management platform.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  In large-scale scenarios, we will continue to reduce the access delay, save the resources consumed, and enhance the stability of the system under high concurrency conditions.
```suggestion
In large-scale scenarios, we will continue to reduce the access latency, resources consumed, and stability impact on the system under high concurrency.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **Multi-cluster observability**. Multi-cluster observability is an important part of a multi-cluster orchestration.
```suggestion
* **Multi-cluster observability**. Multi-cluster observability is an important part in multi-cluster orchestration.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  - We will continue to explore integrated solutions for monitoring and logging at the multi-cloud era.
```suggestion
  - We will continue to explore integrated solutions for multi-cloud monitoring and logging.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  - When the plug-in is coupled with the cluster, how to simplify the installation of the plug-in in the target cluster and manage the lifecycle of the plug-in is our next major research direction.
```suggestion
  - For plug-ins coupled with the cluster, we will dive into simplifying the plug-in installation and lifecycle management.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  - When applications have sequential relationships between clusters, we should provide a multi-cluster workflow to simplify the deployment of these applications.
```suggestion
  - When applications have sequential relationships between clusters, we aim to provide a multi-cluster workflow to simplify the deployment of these applications.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +The planed new features are shown in [roadmap](https://github.com/karmada-io/karmada/blob/master/ROADMAP.md).
```suggestion
The planned new features are listed in [roadmap](https://github.com/karmada-io/karmada/blob/master/ROADMAP.md).
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +## How the CNCF Can Help
```suggestion
## How CNCF Can Help
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +- More channels to advocate the project.
```suggestion
- More channels for exposure
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +- More chances to collaborate with other projects in CNCF or even out of CNCF.
```suggestion
- More chances to collaborate with other projects, both CNCF or non-CNCF ones.
```

2022-10-26 04:14 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +- Technical writing support for project documents.
```suggestion
- Technical writing support
```

2022-10-26 07:39 UTC, Tingtal requested changes
Language polishing (part 3)

2022-10-26 07:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **Vivo** is a tech company that designs and develops smartphones, smartphone accessories, software and online services. To better manage a large-scale cloud native infrastructure, Vivo has the foll
```suggestion
* **Vivo** is a tech company that designs and develops smartphones, smartphone accessories, software and online services. To better manage their large-scale cloud native infrastructure, Vivo requires the following capabilities: 1) Unified management of multiple Kubernetes clusters and resource management by application; 2) Cross-cluster auto scaling and scheduling for
```

2022-10-26 07:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  achieve rational utilization of cross-cluster resources. 3) Dynamic migration of applications to guarantee quick recovery in case of failure. 4) It has the ability to improve the disaster.
```suggestion
  more efficient use of cross-cluster resources; 3) Dynamic migration of applications for quick failover; 4) Better DR
```

2022-10-26 07:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  To solve the above problem, Vivo finally chooses Karmada. In the words of Zhang Rong at Vivo:
```suggestion
  To obtain the above capabilities, Vivo chooses Karmada. According to Zhang Rong from Vivo:
```

2022-10-26 07:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +* **Trip.com** is a Chinese multinational online travel company that provides services including accommodation reservation, transportation ticketing, packaged tours and corporate travel management. B
```suggestion
* **Trip.com** is a Chinese multinational online travel company that provides services including accommodation reservation, transportation ticketing, packaged tours and corporate travel management. Before using Karmada, Trip.com used KubeFed to build their multi-cloud container platform. However, KubeFed uses non-native Kubernetes APIs, which makes it difficult to migrate existing clusters to their multi-cloud platform. The KubeFed community is also becoming inactive.
```

2022-10-26 07:39 UTC, Tingtal commented on cncf_process/2022_karmada_annual/2022-karmada-annual.md
> +  So Trip.com seeks a multi-cloud container platform with smooth migration from KubeFed. Besides, it hopes that the platform can have cross-cluster elastic scaling and scheduling capabilities. In the
```suggestion
  So Trip.com seeks smooth migration from KubeFed, as well as cross-cluster auto scaling and scheduling for their multi-cloud platform. Yue HongHui from Trip.com said:
```

2022-10-28 06:22 UTC, RainbowMango approved these changes
/lgtm
/approve

Thanks @Tingtal

2022-10-28 06:22 UTC, merged